background_css: "#ffffff url('../images/light-pattern.png') repeat top left"
collection_name: start
colour_background: "#000000"
colour_background_accent: "#111111"
colour_background_accent_light: "#777777"
colour_background_accent_lighter: "#333333"
colour_label_text: "#ffffff"
colour_primary_accent: "#0d47a1"
colour_results_list_divider: "#222222"
colour_text: "#eeeeee"
custom_image_filename: favicon.png
custom_image_height: 3rem
typesense_api_key: <value>
typesense_host: ts.example.com
typesense_port: 443
typesense_search_only_api_key: <value>
yaml_link_file: links.yml
